default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_rial_news_development
  username: vagrant
  password: ror2024
  host: localhost
  port: 54320

# test:
#   <<: *default
#   database: the_rial_news_test
#   username: vagrant
#   password: ror2024
#   host: localhost
#   port: 54320

production:
  <<: *default
  database: the_rial_news_production
  username: the_rial_news
  password: <%= ENV["THE_RIAL_NEWS_DATABASE_PASSWORD"] %>
